### ISSUE TITLE
显示账号登陆成功后崩溃

### ISSUE THREAD

**Issue by poly000** [LiveStreamHelper/BiliBiliHelper#71]
```
Traceback (most recent call last):
  File "/home/poly/BiliBiliHelper/main.py", line 128, in <module>
    Auth.work()
  File "/home/poly/BiliBiliHelper/Src/Auth.py", line 30, in work
    self.loginPassword()
  File "/home/poly/BiliBiliHelper/Src/Auth.py", line 47, in loginPassword
    self.getToken(user, base64.b64encode(crypt))
  File "/home/poly/BiliBiliHelper/Src/Auth.py", line 134, in getToken
    account["Token"]["ACCESS_TOKEN"] = data["data"]["token_info"]["access_token"]
KeyError: 'token_info'

```

python 3.9

**Comment by poly000** [comment]
可以收到帮助 但是功能都不可用
